language: java
jdk: oraclejdk8
install: true
cache:
  directories:
  - $HOME/.m2
script:
  - mvn clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
services:
  - mysql
sudo: true
before_script:
  - bash ..travis.install-mysql-5.7.sh