language: java
jdk: oraclejdk8
install: true
cache:
  directories:
  - $HOME/.m2
script:
  - mvn clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('YES') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pnew_password
  - sudo service mysql restart